const MOVIES = {
  FETCH_POPULAR: "FETCH_POPULAR_MOVIES",
  FETCH_BY_KEYWORD: "FETCH_BY_KEYWORD",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",
  CHANGE_SEARCH_KEYWORD: "CHANGE_SEARCH_KEYWORD",
};

export { MOVIES };
